### ISSUE TITLE
[Bug]: .build-and-release.sh added in 2.0.0

### ISSUE THREAD

**Issue by vitorgalvao** [chrisgrieser/alfred-pass#3]
### Bug Description

In 2.0.0, a `.build-and-release.sh` file was added to the root of the workflow. Not a big deal at all, but doesn’t seem intentional.

### Debugging Log

```Text
N/A
```

### Workflow Configuration

N/A

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-pass/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
thx, missed changing the name of the file in the github action. Fixed.
