### ISSUE TITLE
Feature Request: alternative to sourcing ~/.zshenv for PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by 00dani** [chrisgrieser/alfred-pass#4]
### Feature Requested

Currently alfred-pass discovers your PASSWORD_STORE_DIR by calling `app.doShellScript('source ~/.zshenv; echo "$PASSWORD_STORE_DIR"')`, falling back on the default store directory if this fails or does not return a path. This is fine for simple cases, but there's a problem: the `doShellScript()` command always uses `sh` rather than your login shell, and `sh` doesn't understand any Zsh-specific syntax.

Therefore if your `~/.zshenv` happens to use any of that syntax - [say, a glob qualifier](https://git.00dani.me/dot/zsh/src/branch/main/dot-config/zsh/zshenv.zsh) - then alfred-pass will fail to source it and will always fall back on using the default password store directory instead.

I've done some experimentation on possible alternative ways to discover this configuration. Probably the most obvious way would be simply to use Zsh instead of `sh`. This can be achieved by replacing the existing source call with something like `app.doShellScript('exec zsh -c \'echo "$PASSWORD_STORE_DIR"\'')`. I believe the performance characteristics should be fairly similar for any `~/.zshenv` that worked previously, since it's running exactly the same startup script through a different shell.

If for whatever reason making this change isn't viable, I came up with a few other possibilities, which could be provided in addition to the existing behaviour:
- A call to `app.doShellScript('launchctl getenv PASSWORD_STORE_DIR')` works perfectly in my case, because I've manually set that variable in launchd using [EnvPane](https://github.com/hschmidt/EnvPane). This call also safely returns nothing if the variable doesn't exist, and it's quick because it's not evaluating your shell startup script at all and just asks launchd what to do. It does however require the user to set their environment up using EnvPane or another MacOS-specific tool, rather than a generic shell startup file.
- It would be possible for alfred-pass to add an explicit user preference for setting the password store dir, using the Configuration Builder section in the (x) workflow config. These preferences are passed to scripts as environment variables automatically, so simply naming a preference `PASSWORD_STORE_DIR` would do the trick. In this case there's no extra processing required at all, since the variable is already set ahead of time.

Thoughts? I think this would help out Zsh power users who do fancy things in our startup scripts, who are also the prime target audience for a workflow like this one.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Good point, haven't thought about that case.

Fixed in 2.1.1: https://github.com/chrisgrieser/alfred-pass/releases/tag/2.1.1

**Comment by 00dani** [comment]
This change is working excellently for searching and copying existing passwords (yay, transient flag!), but there seems to be a problem when generating a new password: the folder selection step displays folders inside the workflow's own directory, instead of inside my password store.

I think this is because [select-folder-for-new-pw.js](https://github.com/chrisgrieser/alfred-pass/blob/main/scripts/select-folder-for-new-pw.js) is also a JXA script rather than a shell script, and it's figuring out the password store directory in the same way pass-cli-search.js was previously?

**Comment by chrisgrieser** [comment]
...you were so thorough in your initial post that I didn't check for other locations :P

Anyway, both are fixed: https://github.com/chrisgrieser/alfred-pass/releases/download/2.1.3/alfred-pass.alfredworkflow

Btw, if you already found the issue and have a fix, you are very welcome to make a PR
