### ISSUE TITLE
Feature Request: fuzzy search for password entries

### ISSUE THREAD

**Issue by Bounga** [chrisgrieser/alfred-pass#5]
### Feature Requested

Hi ! First things first, thank you for your great Alfred extension.

Now, my feature request.

The recommended way of storing entries in pass is to use a path like `websites/github.com/me@email.org`.

In the current version, if I want to find this entry I have to type `me@email` and scroll in every entries to find the one matching `github.com` by looking at the hint under below the entry. I have a lot of accounts that use the same email address so it's a bit tedious.

I'd like to be able to type `githu` that would trigger a fuzzy search and display all entries matching `githu` in the entry path. Ultimately it would be nice to be able to do something like `gith me@email` to narrow search.

So the search should use the whole path rather than just the username /. last part of the path.

There's an old Alfred pass extension that allow to do this (https://github.com/Ch00k/alfred-pass) maybe it can help implement the same behaviour in your extension?

If I could be of any help I'd be more than happy to help.

### Relevant Screenshot

<img width="720" alt="image" src="https://github.com/user-attachments/assets/49d05ccd-a1bc-4978-b115-651a22dd8f07">

<img width="711" alt="image" src="https://github.com/user-attachments/assets/10f6f71a-f183-4c06-8557-ca0f68adbdca">

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
> The recommended way of storing entries in pass is to use a path like websites/github.com/me@email.org.

Is it really the recommended way? I store the username/mail in the gpg file itself, and looking at the pass website, it looks like they do the same?

---

Anyway, also matching password groups (folders) makes sense nonetheless, and it is easy to implement, so I just added it.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-pass/releases/download/2.3.0/alfred-pass.alfredworkflow

**Comment by Bounga** [comment]
thank you, you rock!
